name: card_game
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^1.14.1
  cloud_firestore: ^3.1.12
  stop_watch_timer: ^1.3.1
  function_tree: ^0.8.12
  font_awesome_flutter: ^10.1.0
  google_fonts: ^2.3.1
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/